[theme]

# Primary color for interactive elements (buttons, sliders, etc.)
primaryColor = "#ef4656"
# Main background color
backgroundColor = "#000000"
# Background color for sidebar and containers
secondaryBackgroundColor = "#3d3d3d"
# Text color
textColor = "#ffffff"
# Font family
font = "sans-serif"